phrase:
  file_format: nested_json
  push:
    sources:
      - file: ./locales/en.yml
        project_id: 6c04f5135e02f03316d753c8b3b54dea
        params:
          locale_id: en
  pull:
    targets:
      - file: ./locales/<locale_name>.json
        project_id: 6c04f5135e02f03316d753c8b3b54dea
        params:
          include_empty_translations: true
          exclude_empty_zero_forms: true
